# Generated by Django 5.0.4 on 2024-07-30 12:52

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Compatibilidade_EducaCenso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nivel', models.CharField(choices=[('1', 'Médio'), ('2', 'Superior')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Deficiencia_aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dia', models.CharField(max_length=10)),
                ('numero_dia', models.IntegerField()),
            ],
            options={
                'ordering': ['numero_dia'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem_historico', models.FloatField(null=True)),
                ('n_A', models.BooleanField(default=False, null=True, verbose_name='Destacar como N/S (Não avaliado) nos impressos')),
                ('faltas', models.BooleanField(default=False, null=True, verbose_name='Não permitir lançamento de faltas')),
                ('notas', models.BooleanField(default=False, null=True, verbose_name='Não permitir lançamento de notas')),
                ('historico_escolar', models.BooleanField(default=False, null=True, verbose_name='Não mostrar no histórico escolar')),
                ('papeletas', models.BooleanField(default=False, null=True, verbose_name='Não mostrar em papeletas')),
                ('ata_final', models.BooleanField(default=False, null=True, verbose_name='Não mostrar em Atas Finais')),
            ],
            options={
                'ordering': ['ordem_historico'],
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculdades_ou_Escolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrauEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Grau/Nível Escolar')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pais_origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Remanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ativo', 'Na Turma'), ('Transferido', 'Noturno'), ('Desistente', 'Desistente/Evasão Escolar')], default='Ativo', max_length=26, verbose_name='Tipo de remanejamento')),
                ('description', models.TextField(max_length=500, verbose_name='Descreva o motivo do Remanejamento. Ex.: Escola para onde o aluno será remanejado e o porquê.')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoRoupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comprimento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.ano')),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='Nome completo do aluno', max_length=120, verbose_name='Nome completo do aluno*')),
                ('nome_social', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento*')),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('tel_celular_aluno', models.CharField(max_length=30, verbose_name='Nº de telefone do aluno*')),
                ('email', models.EmailField(max_length=200, verbose_name='Email*')),
                ('rua', models.CharField(default='Av., Rua, Travessa', max_length=30)),
                ('nome_mae', models.CharField(default='Nome completo da Mãe', max_length=120, verbose_name='Nome da Mãe*')),
                ('tel_celular_mae', models.CharField(max_length=30, null=True, verbose_name='Nº do celular do mãe*')),
                ('nome_pai', models.CharField(default='Nome completo da Pai', max_length=120, null=True)),
                ('tel_celular_pai', models.CharField(max_length=30, null=True)),
                ('naturalidade', models.CharField(default='Cidade onde nasceu', max_length=30)),
                ('aluno_exterior', models.BooleanField(default=False, verbose_name='Marque se o aluno veio do Exterior')),
                ('data_entrada_no_pais', models.DateField(blank=True, null=True)),
                ('documento_estrangeiro', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_sanguineo', models.CharField(choices=[('1', 'A+'), ('5', 'AB+'), ('6', 'AB-'), ('3', 'B+'), ('2', 'A-'), ('4', 'B-'), ('0', 'Não informado'), ('7', 'O+'), ('8', 'O-')], max_length=3, null=True)),
                ('beneficiario_aux_Brasil', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno é beneficiário do Bolsa Família/Aux. Brasil')),
                ('necessita_edu_especial', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno precisa de algum atendimento especial')),
                ('sindrome_de_Down', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno for portador de Síndrome de Down')),
                ('quilombola', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno possui deficiência')),
                ('irmao_gemeo', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno possui irmão(s) gêmeos')),
                ('vacina_covid_19', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno tomou vacina contra a covid 19')),
                ('dose_vacina_covid_19', models.IntegerField(blank=True, null=True, verbose_name='Preencha se o aluno tomou alguma dose da covid 19')),
                ('res_cadastro', models.CharField(default='Quem criou o cadastro', max_length=120, null=True)),
                ('res_atualiza_cadastro', models.CharField(default='Quem atualizou', max_length=120, null=True)),
                ('RG', models.CharField(blank=True, default='000.000.00-00', max_length=14, null=True)),
                ('RG_emissao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=5, null=True)),
                ('renda_familiar', models.CharField(blank=True, max_length=7, null=True)),
                ('CPF', models.CharField(blank=True, default='000.000.000-00', max_length=14, null=True)),
                ('login_aluno', models.CharField(blank=True, max_length=10, null=True)),
                ('senha', models.CharField(blank=True, default='12345678', max_length=10, null=True)),
                ('cartao_nacional_saude_cns', models.CharField(blank=True, max_length=20, null=True)),
                ('nis', models.CharField(blank=True, max_length=20, null=True)),
                ('inep', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('6', 'União Estável'), ('5', 'Viúvo'), ('1', 'Solteiro'), ('2', 'Casado'), ('3', 'Separado'), ('4', 'Divorciado')], max_length=13, null=True)),
                ('tipo_certidao', models.CharField(blank=True, choices=[('1', 'Nascimento'), ('2', 'Casamento'), ('3', 'Outras')], max_length=13, null=True)),
                ('numero_certidao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Certidão de Nascimento (Matrícula Única)')),
                ('livro', models.CharField(blank=True, max_length=10, null=True)),
                ('folha', models.CharField(blank=True, max_length=10, null=True)),
                ('termo', models.CharField(blank=True, max_length=10, null=True)),
                ('emissao', models.DateField(blank=True, null=True)),
                ('distrito_certidao', models.CharField(blank=True, max_length=20, null=True)),
                ('cartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('comarca', models.CharField(blank=True, max_length=100, null=True)),
                ('justificativa_falta_document', models.CharField(blank=True, choices=[('1', 'o(a) aluno(a) não possui os documentos pessoais solicitados'), ('2', 'A escola não dispõe ou não recebeu os docum. pessoais do(a) aluno(a)')], max_length=2, null=True, verbose_name='Justificativa da falta de documentação')),
                ('local_diferenciado', models.CharField(blank=True, choices=[('1', 'o(a) aluno(a) não possui os documentos pessoais solicitados'), ('2', 'A escola não dispõe ou não recebeu os docum. pessoais do(a) aluno(a)')], max_length=2, null=True, verbose_name='Local Diferenciado')),
                ('obito', models.BooleanField(blank=True, default=False, null=True)),
                ('data_obito', models.DateField(blank=True, null=True)),
                ('RG_UF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.uf_unidade_federativa')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.bairro')),
                ('cartorio_uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatio_cartorio_UF', to='rh.uf_unidade_federativa')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.cidade')),
                ('cidade_nascimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidade_nascimento', to='rh.cidade', verbose_name='Cidade onde nasceu')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_nascimento', to='rh.uf_unidade_federativa', verbose_name='Estado onde nasceu')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.sexo', verbose_name='Gênero sexual do aluno*')),
                ('deficiencia_aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.deficiencia_aluno', verbose_name='Informe se o aluno possui deficiência*')),
                ('etnia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.etnia', verbose_name='Etnia do aluno*:')),
                ('nacionalidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.nacionalidade', verbose_name='Nacionalidade*')),
                ('pais_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.pais_origem')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_matricula', models.TextField(default='2023-001', max_length=200, null=True)),
                ('data_matricula', models.DateField(auto_now=True)),
                ('escolarizacao_fora', models.CharField(choices=[('1', 'Não recebe'), ('2', 'Em hospital'), ('3', 'Em domicílio')], default=1, max_length=1)),
                ('data_afastamento_inicio', models.DateField(null=True)),
                ('data_afastamento_fim', models.DateField(null=True)),
                ('motivo_afastamento', models.TextField(max_length=200, null=True)),
                ('calcula_media', models.BooleanField(blank=True, default=True, null=True)),
                ('obervacao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_matricula_alunos', to='gestao_escolar.alunos')),
                ('profissional_matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_matricula_alunos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['aluno'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_periodo', models.CharField(max_length=30, null=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fim', models.TimeField(null=True)),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodo_Horario_related', to='gestao_escolar.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='gestao_escolar.horario')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='gestao_escolar.matriculas')),
            ],
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_especializacao', models.CharField(max_length=100, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.cargo')),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.encaminhamentos')),
            ],
        ),
        migrations.CreateModel(
            name='SequenciaDidatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencias_didaticas', to='gestao_escolar.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Serie_Escolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('compatibilidade_EducaCenso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.compatibilidade_educacenso')),
                ('nivel_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.grauescolar')),
            ],
        ),
        migrations.AddField(
            model_name='matriculas',
            name='serie_multiseriada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.serie_escolar'),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='camisa_tamanho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_camisa', to='gestao_escolar.tamanhoroupa'),
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nome', models.CharField(max_length=14, null=True)),
                ('final', models.BooleanField(default=False)),
                ('ano_letivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.anoletivo')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_aulas_semana', models.IntegerField(default=5, null=True)),
                ('quant_aulas_dia', models.IntegerField(default=3, null=True)),
                ('carga_horaria_anual', models.IntegerField(null=True)),
                ('limite_faltas', models.IntegerField(null=True)),
                ('auxiliar_classe', models.ManyToManyField(null=True, related_name='auxiliarClasse_related', to='gestao_escolar.profissionais')),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.disciplina')),
                ('professo2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradeProfessor2_related', to='gestao_escolar.profissionais')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradeProfessor1_related', to='gestao_escolar.profissionais')),
                ('reserva_tecnica', models.ManyToManyField(null=True, related_name='reservaTecnica_related', to='gestao_escolar.profissionais')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='quarta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarta_prof', to='gestao_escolar.turmadisciplina'),
        ),
        migrations.AddField(
            model_name='horario',
            name='quinta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quinta_prof', to='gestao_escolar.turmadisciplina'),
        ),
        migrations.AddField(
            model_name='horario',
            name='segunda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segunda_prof', to='gestao_escolar.turmadisciplina'),
        ),
        migrations.AddField(
            model_name='horario',
            name='sexta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexta_prof', to='gestao_escolar.turmadisciplina'),
        ),
        migrations.AddField(
            model_name='horario',
            name='terca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terca_prof', to='gestao_escolar.turmadisciplina'),
        ),
        migrations.CreateModel(
            name='GestaoTurmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('faltas', models.IntegerField(blank=True, null=True)),
                ('profissional_resp', models.CharField(max_length=40, null=True)),
                ('data_hora_mod', models.DateTimeField(null=True)),
                ('faltas_total', models.IntegerField(blank=True, null=True)),
                ('recuperacao_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conselho_classe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestao_turmas_related', to='gestao_escolar.matriculas')),
                ('trimestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.trimestre')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.turmadisciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('descritivo_turma', models.CharField(default='única', max_length=10)),
                ('turno', models.CharField(choices=[('Verspertino', 'Verspertino'), ('Noturno', 'Noturno'), ('Matutino', 'Matutino')], default=1, max_length=12)),
                ('quantidade_vagas', models.CharField(default=36, max_length=2)),
                ('turma_multiserie', models.BooleanField(default=False, null=True)),
                ('turma_concluida', models.BooleanField(default=False, null=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.anoletivo')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.escola')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.serie_escolar')),
            ],
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradeTurma_related', to='gestao_escolar.turmas'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.turmas'),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_matricula_turma', to='gestao_escolar.turmas'),
        ),
        migrations.AddField(
            model_name='horario',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turma_Horario_related', to='gestao_escolar.turmas'),
        ),
        migrations.CreateModel(
            name='Validade_horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_validade', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
                ('horario_ativo', models.BooleanField(default=False)),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_validade_related', to='rh.escola')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turma_Validade_related', to='gestao_escolar.turmas')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='validade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turma_Horario_related', to='gestao_escolar.validade_horario'),
        ),
    ]
