# Generated by Django 5.0.4 on 2024-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0535_alter_alunos_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('1', 'Solteiro'), ('5', 'Viúvo'), ('4', 'Divorciado'), ('6', 'União Estável'), ('3', 'Separado'), ('2', 'Casado')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('7', 'O+'), ('2', 'A-'), ('6', 'AB-'), ('4', 'B-'), ('5', 'AB+'), ('8', 'O-'), ('0', 'Não informado'), ('3', 'B+'), ('1', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='turno',
            field=models.CharField(choices=[('Noturno', 'Noturno'), ('Verspertino', 'Verspertino'), ('Matutino', 'Matutino')], default=1, max_length=12),
        ),
    ]
