# Generated by Django 5.0.4 on 2024-07-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '1042_alter_alunos_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('6', 'União Estável'), ('1', 'Solteiro'), ('4', 'Divorciado'), ('2', 'Casado'), ('3', 'Separado'), ('5', 'Viúvo')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('7', 'O+'), ('1', 'A+'), ('8', 'O-'), ('6', 'AB-'), ('2', 'A-'), ('0', 'Não informado'), ('3', 'B+'), ('5', 'AB+'), ('4', 'B-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(choices=[('2', 'Superior'), ('1', 'Médio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='remanejamento',
            name='tipo',
            field=models.CharField(choices=[('Ativo', 'Na Turma'), ('Desistente', 'Desistente/Evasão Escolar'), ('Transferido', 'Noturno')], default='Ativo', max_length=26, verbose_name='Tipo de remanejamento'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='turno',
            field=models.CharField(choices=[('Noturno', 'Noturno'), ('Matutino', 'Matutino'), ('Verspertino', 'Verspertino')], default=1, max_length=12),
        ),
    ]
