# Generated by Django 5.0.4 on 2024-07-30 15:36

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeclaturaJanelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(default='', max_length=50)),
                ('notas', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaletaCores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paleta', models.CharField(default='Paleta Branca', max_length=20)),
                ('cor_primaria', models.CharField(default='#fff', max_length=7)),
                ('cor_secundaria', models.CharField(default='#fff', max_length=7)),
                ('cor_sucesso', models.CharField(default='#fff', max_length=7)),
                ('cor_info', models.CharField(default='#fff', max_length=7)),
                ('cor_aviso', models.CharField(default='#fff', max_length=7)),
                ('cor_perigo', models.CharField(default='#ffffff', max_length=7)),
                ('cor_texto', models.CharField(default='#000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MessageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto da mensagem')),
                ('mensagem', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('aberta', models.BooleanField(default=False)),
                ('foi_consultado', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('exclude_msg', models.CharField(blank=True, max_length=5, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário da mensagem')),
                ('remetente', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente da mensagem')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-data_envio'],
            },
        ),
    ]
