# Generated by Django 5.0.4 on 2024-07-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(default='2023', max_length=4, verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Config_plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('rh_Ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(default='', max_length=60, verbose_name='Nome da Escola ou Departamento')),
                ('endereco_escola', models.CharField(default='', max_length=100, verbose_name='Endereço')),
                ('telefone_escola', models.CharField(default='', max_length=30, null=True, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descreva a profissão')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Texto_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('professor', 'Professor'), ('funcionario', 'Funcionário'), ('estagio', 'Estágio'), ('voluntario', 'Voluntário')], max_length=20)),
                ('texto', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uf_Unidade_Federativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=50)),
                ('nome_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('data_nascimento', models.DateField(null=True)),
                ('idade', models.CharField(blank=True, max_length=9, null=True)),
                ('cpf', models.CharField(max_length=30, null=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=30, null=True, verbose_name='RG')),
                ('rua', models.CharField(max_length=50, null=True, verbose_name='Nome da rua, avenida etc.')),
                ('complemento', models.CharField(max_length=30, null=True, verbose_name='casa, apartamento etc.')),
                ('numero_casa', models.CharField(max_length=10, null=True, verbose_name='Numero da casa ou s/n')),
                ('cep', models.CharField(max_length=30, null=True, verbose_name='CEP')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_bairro_related', to='rh.bairro', verbose_name='Bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_cidade_related', to='rh.bairro', verbose_name='Cidade')),
                ('nome_profissao', models.ManyToManyField(blank=True, to='rh.profissao', verbose_name='Profissões')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_contrato', models.DateField(auto_now_add=True)),
                ('data_fim_contrato', models.DateField(null=True)),
                ('tempo_meses', models.IntegerField(null=True)),
                ('ano_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ano_contrato_related', to='rh.ano', verbose_name='Ano do contrato')),
                ('nome_escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.escola', verbose_name='Escola que o profissional irá desempenhar suas funções')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_contratada', to='rh.pessoas', verbose_name='Pessoa a ser contratada')),
                ('nome_profissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.profissao', verbose_name='Função que irá desempenhar na escola')),
            ],
            options={
                'ordering': ['ano_contrato'],
            },
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefeitura_nome', models.CharField(default='Prefeitura', max_length=50)),
                ('instituto', models.CharField(default='Nome da Instituição', max_length=50)),
                ('endereco', models.CharField(default='', max_length=50, null=True)),
                ('pessoa_publica', models.CharField(default='', max_length=30)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefeitura_cidade_related', to='rh.cidade')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefeitura_estado_related', to='rh.uf_unidade_federativa')),
            ],
        ),
        migrations.AddField(
            model_name='escola',
            name='prefeitura',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='rh.prefeitura', verbose_name='Nome da Instituição Responsável'),
        ),
        migrations.CreateModel(
            name='Frequencia_mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=30, verbose_name='Mês')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia_ano', to='rh.ano')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_frequencia', to='rh.escola', verbose_name='Local onde o profissional será encaminhado')),
                ('profissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequencia_profissional', to='rh.profissao', verbose_name='Frequência do profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Encaminhamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encaminhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamento_escolar', to='rh.contrato', verbose_name='Profissional a ser encaminhado')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_encaminhamento', to='rh.escola', verbose_name='Local onde o profissional será encaminhado')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.profissao', verbose_name='Atividade a ser realizada pelo profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Decreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_decreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ano_decreto', to='rh.ano', verbose_name='Ano do')),
                ('destino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_decreto', to='rh.escola', verbose_name='Local onde o profissional será encaminhado')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decreto_profissional', to='rh.pessoas', verbose_name='Profissional em que foi emitido o decreto')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.profissao', verbose_name='Atividade a ser realizada pelo profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargaHoraria', models.IntegerField(null=True, verbose_name='Carga horária para o valor vigente')),
                ('valor', models.CharField(max_length=100, null=True, verbose_name='Valor do salário')),
                ('ano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.ano', verbose_name='Ano em que o valor do salário está vigente')),
                ('profissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.profissao', verbose_name='Profissão atendida pelo valor do salário')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='salario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.salario', verbose_name='Valor do salário para o cargo escolhido. Atente-se para o ano em que o valor do salário está vigente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='text_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Texto_contrao_related', to='rh.texto_contrato', verbose_name='Vinculo com o tipo de contrato'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='nome_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.uf_unidade_federativa'),
        ),
        migrations.CreateModel(
            name='Vinculo_empregaticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('efetivo', 'efetivo'), ('contrato', 'Contrato'), ('decreto', 'Decreto'), ('estagio', 'estagio')], max_length=10, null=True)),
                ('ano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.ano')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.pessoas')),
            ],
        ),
    ]
