# Generated by Django 5.0.4 on 2024-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('efetivo', 'efetivo'), ('decreto', 'Decreto'), ('estagio', 'estagio')], max_length=10, null=True),
        ),
    ]
