# Generated by Django 5.0.4 on 2024-07-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0071_alter_vinculo_empregaticio_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('decreto', 'Decreto'), ('contrato', 'Contrato'), ('estagio', 'estagio'), ('efetivo', 'efetivo')], max_length=10, null=True),
        ),
    ]
