# Generated by Django 5.0.4 on 2024-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0851_alter_vinculo_empregaticio_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('efetivo', 'efetivo'), ('contrato', 'Contrato'), ('estagio', 'estagio'), ('decreto', 'Decreto')], max_length=10, null=True),
        ),
    ]
