from .GE_pasta_escola import *
from .pasta_session import *
from .ano_letivo import *
from .turmas import *
from .disciplinas import *
from .grades import *
from .gestao_turma import *
from .alunos import *
from .matriculas import *
from .remanejamento import *
from .professores import *
from .cria_qrcode import *
from .impressos import *
from .bairro import *
from .cidade import *
from .minhaEscola import *
from .decretos import *
from .pessoas import *
#from .ferramentas import *
